init:
  # On 17-04-09, MVS versions 9, 10, 11, 12, and 14 were available.  Each later
  # version makes a larger EXE, presumably because there are more optimization
  # paths in later versions.
  # - call "C:\\Program Files (x86)\\Microsoft Visual Studio 9.0\\VC\\vcvarsall.bat" x86
  # - call "C:\\Program Files (x86)\\Microsoft Visual Studio 10.0\\VC\\vcvarsall.bat" x86
  # - call "C:\\Program Files (x86)\\Microsoft Visual Studio 11.0\\VC\\vcvarsall.bat" x86
  # - call "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\vcvarsall.bat" amd64_x86
  - call "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\vcvarsall.bat" amd64_x86

build_script:
  - nmake
  - dir gv.exe gvlib.lib mem.lib

artifacts:
  - path: gv.exe
  - path: gvlib.lib
  - path: mem.lib

deploy:
  - provider: GitHub
    tag: 'gv-latest'
    release: 'Release gv-latest'
    auth_token:
      secure: PGsGUDU6oqIy7zCyTMwIWlzf4TbJtuIgqmWb9ZLqNlM13AAaxWfDlzDlG+0CyHFx
    artifact: gv.exe, gvlib.lib, mem.lib
    force_update: true
    on:
      branch: master

  - provider: GitHub
    tag: $(appveyor_repo_tag_name)
    release: Release $(appveyor_repo_tag_name)
    auth_token:
      secure: PGsGUDU6oqIy7zCyTMwIWlzf4TbJtuIgqmWb9ZLqNlM13AAaxWfDlzDlG+0CyHFx
    artifact: gv.exe, gvlib.lib, mem.lib
    force_update: true
    on:
      appveyor_repo_tag: true
